name: Deploy to Vercel (Preview)
description: Deploys a prebuilt preview artifact to Vercel and outputs the deployment URL.

inputs:
  vercel-token:
    description: Vercel token.
    required: true
  vercel-org-id:
    description: Vercel org id.
    required: true
  vercel-project-id:
    description: Vercel project id.
    required: true

outputs:
  exit_code:
    description: Exit code from vercel deploy.
    value: ${{ steps.run.outputs.exit_code }}
  deploy_url:
    description: Parsed deployment URL.
    value: ${{ steps.run.outputs.deploy_url }}

runs:
  using: composite
  steps:
    - id: run
      name: Deploy
      run: python3 "${{ github.action_path }}/src/main.py"
      shell: bash
