name: Update Status on Preview Deployment Success
description: Creates or updates a PR comment with the Vercel preview URL for workflow_run preview deployments.

inputs:
  github-token:
    description: GitHub token used to create/update PR comments.
    required: true
  preview-url:
    description: Preview URL output from the Vercel deploy step (optional, action will fallback to Vercel API lookup).
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Upsert preview deployment comment
      run: python3 "${{ github.action_path }}/src/main.py"
      shell: bash
