name: Check Prerequisites and Locate Build Artifact
description: Verifies required workflow runs succeeded for a SHA and returns the build artifact download URL.

inputs:
  github-token:
    description: GitHub token used to query workflow runs and artifacts.
    required: true
  sha:
    description: Commit SHA to verify.
    required: true
  trigger-event:
    description: workflow_run.event (or current event) for additional gating.
    required: false
    default: ""
  head-branch:
    description: Head branch (for hotfix gating).
    required: false
    default: ""
  is-fork:
    description: "'true' if PR head repo is a fork."
    required: false
    default: "false"
  skip-hotfix:
    description: "'true' to skip when head branch starts with hotfix/."
    required: false
    default: "false"
  skip-forks:
    description: "'true' to skip when is-fork is true."
    required: false
    default: "false"
  require-trigger-event:
    description: If set, only deploy when trigger-event matches.
    required: false
    default: ""
  build-workflow-file:
    description: Workflow file name that produced the artifact (e.g. build-preview.yml).
    required: true
  artifact-name:
    description: Artifact name to download.
    required: true
  required-workflows-json:
    description: JSON array of {id,label} workflow descriptors that must have a successful run for the SHA.
    required: true

outputs:
  should_deploy:
    description: "'true' if all prerequisites succeeded and artifact exists."
    value: ${{ steps.run.outputs.should_deploy }}
  artifact_download_url:
    description: Artifact archive download URL.
    value: ${{ steps.run.outputs.artifact_download_url }}

runs:
  using: composite
  steps:
    - id: run
      name: Verify prerequisites
      working-directory: ${{ github.action_path }}
      run: python3 src/main.py
      shell: bash
