name: Fail Workflow if Deploy Failed
description: Fails the workflow if exit-code is non-zero.

inputs:
  exit-code:
    description: Exit code from deploy step.
    required: true

runs:
  using: composite
  steps:
    - name: Fail if non-zero
      working-directory: ${{ github.action_path }}
      run: python3 src/main.py
      shell: bash
