name: Lint and Unit Tests Pass
description: Verifies Lint and Unit Tests jobs succeeded for the triggering workflow_run.

inputs:
  github-token:
    description: GitHub token used to query workflow run jobs.
    required: true

runs:
  using: node20
  main: dist/index.mjs
