name: Resolve Deploy SHA
description: Resolves the SHA and basic context for workflow_run or workflow_dispatch triggered deploy workflows.

outputs:
  sha:
    description: Commit SHA to deploy.
    value: ${{ steps.run.outputs.sha }}
  trigger_event:
    description: Triggering event for the source workflow (workflow_run.event) or current event.
    value: ${{ steps.run.outputs.trigger_event }}
  head_branch:
    description: Head branch for workflow_run or current ref name.
    value: ${{ steps.run.outputs.head_branch }}
  is_fork:
    description: Whether the PR head repo is a fork (workflow_run only).
    value: ${{ steps.run.outputs.is_fork }}

runs:
  using: composite
  steps:
    - id: run
      name: Resolve context
      working-directory: ${{ github.action_path }}
      run: python3 src/main.py
      shell: bash
