name: Preview Failure Comment
description: Comment on the PR when the Vercel preview deployment fails for workflow_run deployments.

inputs:
  github-token:
    description: GitHub token used to create PR comments.
    required: true
  preview-url:
    description: Preview URL output from the Vercel deploy step (optional, action will fallback to Vercel API lookup).
    required: false
    default: ""

runs:
  using: node20
  main: dist/index.mjs
