name: Install Vercel CLI (Pinned)
description: Installs a pinned version of the Vercel CLI globally.

inputs:
  version:
    description: Vercel CLI version.
    required: true

runs:
  using: composite
  steps:
    - name: Install CLI
      run: python3 "${{ github.action_path }}/src/main.py"
      shell: bash
