name: Update Status on Preview Deployment Failure
description: Comments on the PR when a workflow_run preview deployment fails.

inputs:
  github-token:
    description: GitHub token used to create PR comments.
    required: true
  preview-url:
    description: Preview URL output from the Vercel deploy step (optional, action will fallback to Vercel API lookup).
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Create preview failure comment
      run: python3 "${{ github.action_path }}/src/main.py"
      shell: bash
