name: Deployment Preview Comment (Failure)
description: Comments on the PR when a workflow_run preview deployment fails.

inputs:
  github-token:
    description: GitHub token used to create PR comments.
    required: true
  preview-url:
    description: Preview URL output from the Vercel deploy step (optional, action will fallback to Vercel API lookup).
    required: false
    default: ""

runs:
  using: node20
  main: dist/index.mjs
