import type { APIRoute } from 'astro'

export const prerender = true

const OFFLINE_CACHE = 'webstackbuilders-offline-v1'
const ASSET_CACHE = 'webstackbuilders-assets-v1'
const IMAGE_CACHE = 'webstackbuilders-images-v1'
const OFFLINE_URL = '/offline'

export const buildServiceWorkerScript = (): string => {
  return [
    `const OFFLINE_CACHE = '${OFFLINE_CACHE}'`,
    `const ASSET_CACHE = '${ASSET_CACHE}'`,
    `const IMAGE_CACHE = '${IMAGE_CACHE}'`,
    `const OFFLINE_URL = '${OFFLINE_URL}'`,
    '',
    "self.addEventListener('install', event => {",
    '  event.waitUntil(',
    "    caches.open(OFFLINE_CACHE).then(cache => cache.add(OFFLINE_URL)).catch(() => undefined)",
    '  )',
    '  self.skipWaiting()',
    '})',
    '',
    "self.addEventListener('activate', event => {",
    '  event.waitUntil(self.clients.claim())',
    '})',
    '',
    'const cacheAsset = async (cacheName, request, response) => {',
    '  if (!response || !response.ok) {',
    '    return response',
    '  }',
    '',
    '  const cache = await caches.open(cacheName)',
    '  await cache.put(request, response.clone())',
    '  return response',
    '}',
    '',
    'const staleWhileRevalidate = async request => {',
    '  const cache = await caches.open(ASSET_CACHE)',
    '  const cached = await cache.match(request)',
    '  const network = fetch(request)',
    '    .then(response => cacheAsset(ASSET_CACHE, request, response))',
    '    .catch(() => undefined)',
    '',
    '  if (cached) {',
    '    void network',
    '    return cached',
    '  }',
    '',
    '  return network || fetch(request)',
    '}',
    '',
    'const cacheFirst = async request => {',
    '  const cache = await caches.open(IMAGE_CACHE)',
    '  const cached = await cache.match(request)',
    '  if (cached) {',
    '    return cached',
    '  }',
    '',
    '  const response = await fetch(request)',
    '  return cacheAsset(IMAGE_CACHE, request, response)',
    '}',
    '',
    'const handleNavigation = async request => {',
    '  try {',
    '    return await fetch(request)',
    '  } catch {',
    '    const cachedOffline = await caches.match(OFFLINE_URL)',
    '    if (cachedOffline) {',
    '      return cachedOffline',
    '    }',
    '',
    "    return new Response('Offline', { status: 503, statusText: 'Offline' })",
    '  }',
    '}',
    '',
    "self.addEventListener('fetch', event => {",
    '  const { request } = event',
    "  if (request.method !== 'GET') {",
    '    return',
    '  }',
    '',
    "  if (request.mode === 'navigate') {",
    '    event.respondWith(handleNavigation(request))',
    '    return',
    '  }',
    '',
    "  if (request.destination === 'style' || request.destination === 'script') {",
    '    event.respondWith(staleWhileRevalidate(request))',
    '    return',
    '  }',
    '',
    "  if (request.destination === 'image') {",
    '    event.respondWith(cacheFirst(request))',
    '  }',
    '})',
  ].join('\n')
}

export const GET: APIRoute = _context => {
  return new Response(buildServiceWorkerScript(), {
    headers: {
      'Content-Type': 'application/javascript; charset=utf-8',
      'Cache-Control': 'no-cache, no-store, must-revalidate',
      'Service-Worker-Allowed': '/',
    },
  })
}