name: Require Playwright Success
description: Ensures Playwright workflow completed successfully for a given SHA before proceeding.

inputs:
  github_token:
    description: GitHub token used to call the GitHub API.
    required: true
  expected_sha:
    description: SHA that must have a successful Playwright workflow run.
    required: true
  workflow_file:
    description: Workflow file name for Playwright (e.g. playwright.yml).
    required: false
    default: playwright.yml
  per_page:
    description: Max workflow runs to fetch.
    required: false
    default: '50'

runs:
  using: composite
  steps:
    - name: Require Playwright success
      working-directory: ${{ github.action_path }}
      run: python3 src/main.py
      shell: bash
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_EXPECTED_SHA: ${{ inputs.expected_sha }}
        INPUT_WORKFLOW_FILE: ${{ inputs.workflow_file }}
        INPUT_PER_PAGE: ${{ inputs.per_page }}
        GITHUB_API_URL: ${{ github.api_url }}
        GITHUB_REPOSITORY: ${{ github.repository }}
