name: Update Status on Production Deployment Failure
description: Comments on the commit when a workflow_run production deployment fails.

inputs:
  github-token:
    description: GitHub token used to create commit comments.
    required: true
  preview-url:
    description: Production URL (if available) from the Vercel deployment step.
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Create production failure commit comment
      run: python3 "${{ github.action_path }}/src/main.py"
      shell: bash
