name: Deployment Production Comment (Failure)
description: Comments on the commit when a workflow_run production deployment fails.

inputs:
  github-token:
    description: GitHub token used to create commit comments.
    required: true
  preview-url:
    description: Production URL (if available) from the Vercel deployment step.
    required: false
    default: ""

runs:
  using: node20
  main: dist/index.mjs
