name: Mark Deployment in Progress
description: Sets deployment status to in_progress for a deployment id.

inputs:
  token:
    description: GitHub token used to create deployment statuses.
    required: true
  deployment-id:
    description: Deployment id.
    required: true
  description:
    description: Status description.
    required: true

runs:
  using: composite
  steps:
    - name: Mark in progress
      working-directory: ${{ github.action_path }}
      run: python3 src/main.py
      shell: bash
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_DEPLOYMENT_ID: ${{ inputs.deployment-id }}
        INPUT_DESCRIPTION: ${{ inputs.description }}
