name: Update Deployment Status
description: Updates a GitHub Deployment status to success or failure, optionally setting environment_url.

inputs:
  token:
    description: GitHub token used to create deployment statuses.
    required: true
  deployment-id:
    description: Deployment id.
    required: true
  exit-code:
    description: Exit code from deploy step.
    required: true
  environment-url:
    description: URL to set as the environment_url.
    required: false
    default: ""
  success-description:
    description: Description for success status.
    required: true
  failure-description:
    description: Description for failure status.
    required: true

runs:
  using: composite
  steps:
    - name: Update status
      working-directory: ${{ github.action_path }}
      run: python3 src/main.py
      shell: bash
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_DEPLOYMENT_ID: ${{ inputs.deployment-id }}
        INPUT_EXIT_CODE: ${{ inputs.exit-code }}
        INPUT_ENVIRONMENT_URL: ${{ inputs.environment-url }}
        INPUT_SUCCESS_DESCRIPTION: ${{ inputs.success-description }}
        INPUT_FAILURE_DESCRIPTION: ${{ inputs.failure-description }}
